### ISSUE TITLE
Remove conflict with ppx_sexp_conv >= v0.11.1

### ISSUE THREAD

**Issue by copy** [mirleft/ocaml-x509#107]
As per https://github.com/ocaml/opam-repository/pull/11898#issuecomment-386271141 ppx_sexp_conv>=v0.11.1 does not have a dependency on Base any more, so the compatible versions can be changed from `ppx_sexp_conv < v0.11.0` to `ppx_sexp_conv != v0.11.0`.

I checked that x509 is compilable with newer versions of ppx_sexp_conv (and doesn't suffer from the same bug that nocrypto suffers from).

Related: https://github.com/mirleft/ocaml-tls/issues/379

**Comment by hannesm** [comment]
Dear @copy:

> so the compatible versions can be changed from `ppx_sexp_conv < v0.11.0` to `ppx_sexp_conv != v0.11.0`

I'm sure this will lead to invalid metadata (in the META file of X.509) due to ppx_sexp_conv introducing run-time dependencies.  This is hard to observe (by using opam) since `nocrypto` nowadays already adds the required depedencies into their META file and shadows the insufficient data in X.509 META file.

> I checked that x509 is compilable with newer versions of ppx_sexp_conv (and doesn't suffer from the same bug that nocrypto suffers from).

I'm not exactly sure what you mean.  I hope my description above sheds some light into why X.509 (and tls) are restricted to `ppx_sexp_conv {< "v0.11.0"}` at the moment.

I'll merge #109 and release X.509 for compatibility with newer ppx_sexp_conv.  I hope this works fine for you.

**Comment by hannesm** [comment]
fixed in #109

**Comment by copy** [comment]
> I'm sure this will lead to invalid metadata (in the META file of X.509) due to ppx_sexp_conv introducing run-time dependencies. This is hard to observe (by using opam) since nocrypto nowadays already adds the required depedencies into their META file and shadows the insufficient data in X.509 META file.

You're right about this. Originally I was under the impression that simply adding `ppx_sexp_conv` to the `META` file would work for both ppx_sexp_conv<v0.11.0` and `ppx_sexp_conv>=v0.11.0, but that doesn't seem to be the case.

> I'm not exactly sure what you mean.

I was referring to the original issue here: https://github.com/mirleft/ocaml-nocrypto/issues/143, which is not related to Nocrypto's META files but to its build system (see https://github.com/mirleft/ocaml-nocrypto/pull/144/commits/ee7305febb4486e40bae6d2e791dc9fbe51ee5d2 and https://github.com/mirleft/ocaml-nocrypto/pull/144/commits/a9da8a8883e05460dc98ad8dd616aad46bb82741). I simply stated that x509 doesn't suffer from this problem.

> I'll merge #109 and release X.509 for compatibility with newer ppx_sexp_conv.

Very much appreciated.
