### ISSUE TITLE
X509.CA.sign ignores extensions in the CSR

### ISSUE THREAD

**Issue by reynir** [mirleft/ocaml-x509#63]
Looking at the source it seems to me that `X509.CA.sign` ignores the extensions in the csr and uses the ones optionally passed or no extensions. Is this intentional?

**Comment by hannesm** [comment]
yes, this is intentional. There are various use cases for CAs on how to handle extensions from the CSR and local ones. I don't think the X509 library should decide who overwrites which extensions, thus only the public key information and subject are used from a CSR. You can, before calling `sign`, merge/add/modify the extensions from the CSR yourself and pass them to `sign`.

**Comment by reynir** [comment]
Thanks for the quick reply. That makes perfect sense!

I made a small change to the documentation mentioning this fact.
