### ISSUE TITLE
Add hostnames: csr -> string list  for obtaining list of domains of a csr.

### ISSUE THREAD

**Issue by mmaker** [mirleft/ocaml-x509#82]
Dear brothers and sisters, 

I am using x509 to implement the ACME protocol in ocaml <github.com/mmaker/ocaml-acme>. 
This means that I have to deal with certificate signing requests, and for every domain listed in the request provide a proof to the CA that that domain is indeed owned by the used.
As a more eloquent example of this, take a look at
https://github.com/diafygi/acme-tiny/blob/master/acme_tiny.py#L65-75. 
Later, at line 95 you can see that the client attempts to validate every domain in the signing request. 

Currently I am asking the user the domain to validate as an extra argument, but all the information is already in the csr. I just cannot get it. I would be nice if X509 had implemented such a feature.

**Comment by hannesm** [comment]
sadly it is not trivial, since I fail to find how it is encoded (https://tools.ietf.org/html/rfc2986#page-7 specifies attributes, maybe they hide it in there)... will need to dig into how openssl actually does it at some point... could you in the meantime use the subject (from: https://mirleft.github.io/ocaml-x509/X509.CA.html#TYPErequest_info), which is only a single name...

**Comment by hannesm** [comment]
since I needed this functionality as well, and it is a bit tedious to write (check for SAN extension in CSR, check subject) I'd be keen to adapt it (see code at https://github.com/mmaker/ocaml-letsencrypt/blob/v0.1.0/src/acme_common.ml#L9); also `X509.Certificate.hostnames` is present, and a complementary `X509.Signing_request.hostnames` would be welcome (also resulting in a `Domain_name.Set.t`)
